spring.application.name=demo
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration

spring.datasource.url=jdbc:h2:file:./data/vcrp
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true